// Development tool (NOT part of the intro): measures BRANA's shaders on the
// GPU of a Mac. tools/mac/build.sh cross-compiles it on Linux without the
// Apple SDK (every function comes from dlopen/dlsym, like src/mac/main.asm)
// and also builds a Linux twin with freeglut, for testing it on a PC.
//
//   ./macbench               timings, about 2 minutes. A laptop slows down when
//                            it gets hot, so it first heats the GPU up for 30 s,
//                            then measures the shader variants taking turns
//                            (heat affects them all alike); prints tables
//   ./macbench look          the visuals at 5 internal resolutions (to choose
//                            the smallest acceptable one); any key quits
//   ./macbench play [v] [k]  the intro's visuals in real time (no sound) with
//                            shader variant v (name or number, default current)
//                            at k/16 of the screen resolution (default 16),
//                            then the frame rate of every scene; any key quits
//   The Linux twin also takes a render size: "bench 640 360".
//
// The timings render offscreen into a framebuffer object of the screen size
// and wait for each frame with glFinish, so the display's refresh rate does
// not matter.
#include "variants.h"   // generated by tools/mac/variants.py

typedef unsigned U;
typedef unsigned long long u64;
void *dlopen(const char *, int);
void *dlsym(void *, const char *);

#ifdef __APPLE__
#define ANY ((void *)-2)   // RTLD_DEFAULT
#define FWK "/System/Library/Frameworks/"
#else
#define ANY ((void *)0)
#endif

static int (*printf_)(const char *, ...);
static int (*fflush_)(void *);
static void (*exit_)(int);
#ifdef __APPLE__
static u64 (*clock_ns)(int);
#else
static int (*clock_gettime_)(int, long *);
static void (*glutInitContextVersion)(int, int);
static void (*glutInitContextProfile)(int);
static void (*glutInitContextFlags)(int);
#endif
static void (*glutInit)(int *, char **);
static void (*glutInitDisplayMode)(U);
static int (*glutCreateWindow)(const char *);
static void (*glutFullScreen)(void);
static void (*glutSetCursor)(int);
static void (*glutDisplayFunc)(void (*)(void));
static void (*glutIdleFunc)(void (*)(void));
static void (*glutKeyboardFunc)(void (*)(unsigned char, int, int));
static void (*glutMainLoop)(void);
static void (*glutSwapBuffers)(void);
static int (*glutGet)(U);
static const char *(*glGetString)(U);
static U (*glGetError)(void);
static U (*glCreateShader)(U);
static void (*glShaderSource)(U, int, const char *const *, const int *);
static void (*glCompileShader)(U);
static void (*glGetShaderiv)(U, U, int *);
static void (*glGetShaderInfoLog)(U, int, int *, char *);
static U (*glCreateProgram)(void);
static void (*glAttachShader)(U, U);
static void (*glLinkProgram)(U);
static void (*glGetProgramiv)(U, U, int *);
static void (*glGetProgramInfoLog)(U, int, int *, char *);
static void (*glUseProgram)(U);
static void (*glDeleteProgram)(U);
static int (*glGetUniformLocation)(U, const char *);
static void (*glUniform4f)(int, float, float, float, float);
static void (*glGenVertexArrays)(int, U *);
static void (*glBindVertexArray)(U);
static void (*glDrawArrays)(U, int, int);
static void (*glViewport)(int, int, int, int);
static void (*glGenTextures)(int, U *);
static void (*glBindTexture)(U, U);
static void (*glTexImage2D)(U, int, int, int, int, int, U, U, const void *);
static void (*glGenFramebuffers)(int, U *);
static void (*glBindFramebuffer)(U, U);
static void (*glFramebufferTexture2D)(U, U, U, U, int);
static U (*glCheckFramebufferStatus)(U);
static void (*glReadPixels)(int, int, int, int, U, U, void *);
static void (*glBlitFramebuffer)(int, int, int, int, int, int, int, int, U, U);
static void (*glClearColor)(float, float, float, float);
static void (*glClear)(U);
static void (*glFinish)(void);

#define ROWS (SONG_SAMPLES / 2048 + 1)
static float song[ROWS * 1024 * 4], song2[ROWS * 1024 * 4];
static char log_[4096];
static const char *vs_src = "#version 330\nvoid main(){gl_Position=vec4(gl_VertexID%2*4-1,gl_VertexID/2*4-1,0,1);}";
#define NM 10
static const float moments[NM] = {12, 26, 60, 72, 84, 88, 92, 100, 116, 132};
static const float weights[NM] = {24, 24, 16, 16, 5.3f, 5.3f, 5.4f, 16, 16, 18};   // seconds each moment stands for
static int W, H, look, play, play_v, play_k = 16;
static double start;

static int num(const char *c)
{
	int n = 0;
	while (*c >= '0' && *c <= '9') n = n * 10 + *c++ - '0';
	return n;
}

static int same(const char *a, const char *b)
{
	while (*a && *a == *b) a++, b++;
	return *a == *b;
}

static void *lib(const char *name)
{
	void *h = dlopen(name, 1);
	if (!h) { printf_("cannot load %s\n", name); exit_(1); }
	return h;
}

static void *sym(void *h, const char *name)
{
	void *p = dlsym(h, name);
	if (!p) { printf_("missing function %s\n", name); exit_(1); }
	return p;
}
#define LOAD(h, f) (*(void **)&f = sym(h, #f))

static double now(void)
{
#ifdef __APPLE__
	return clock_ns(8) * 1e-9;   // CLOCK_UPTIME_RAW
#else
	long ts[2];
	clock_gettime_(1, ts);       // CLOCK_MONOTONIC
	return ts[0] + ts[1] * 1e-9;
#endif
}

static void out(void) { fflush_(0); }

static U shader(U type, const char *src)
{
	U s = glCreateShader(type);
	int ok = 0;
	glShaderSource(s, 1, &src, 0);
	glCompileShader(s);
	glGetShaderiv(s, 0x8B81, &ok);   // GL_COMPILE_STATUS
	if (!ok) {
		glGetShaderInfoLog(s, sizeof log_, 0, log_);
		printf_("shader compile FAILED:\n%s\n", log_);
	}
	return s;
}

// program with the intro's vertex shader; returns 0 on failure
static U program(const char *fs)
{
	U p = glCreateProgram();
	int ok = 0;
	glAttachShader(p, shader(0x8B31, vs_src));
	glAttachShader(p, shader(0x8B30, fs));
	glLinkProgram(p);
	glGetProgramiv(p, 0x8B82, &ok);   // GL_LINK_STATUS
	if (!ok) {
		glGetProgramInfoLog(p, sizeof log_, 0, log_);
		printf_("program link FAILED:\n%s\n", log_);
		return 0;
	}
	glUseProgram(p);
	return p;
}

static void tri(void) { glDrawArrays(4, 0, 3); }   // GL_TRIANGLES

// clears pending GL errors, returns the first one
static U err(void)
{
	U e = glGetError(), f = e;
	while (f) f = glGetError();
	return e;
}

// offscreen render target: texture + framebuffer object
static U target(U ifmt, int w, int h, U *tex)
{
	U fb;
	glGenTextures(1, tex);
	glBindTexture(0x0DE1, *tex);
	glTexImage2D(0x0DE1, 0, ifmt, w, h, 0, 0x1908, ifmt == 0x8058 ? 0x1401 : 0x1406, 0);
	glGenFramebuffers(1, &fb);
	glBindFramebuffer(0x8D40, fb);
	glFramebufferTexture2D(0x8D40, 0x8CE0, 0x0DE1, *tex, 0);
	U st = glCheckFramebufferStatus(0x8D40);
	if (st != 0x8CD5) printf_("framebuffer %dx%d format 0x%x NOT complete: 0x%x\n", w, h, ifmt, st);
	return fb;
}

// ms per frame of the current program at time t, rendered at w x h: the
// fastest of 3 batches (each at least min_s / 3 and 2 frames), so that
// other programs running meanwhile distort it less
static double timeit(int loc, float t, int w, int h, double min_s)
{
	glViewport(0, 0, w, h);
	glUniform4f(loc, t, w, h, 0);
	tri();
	glFinish();   // warm-up at this size
	double best = 1e9;
	for (int b = 0; b < 3; b++) {
		int n = 0;
		double t0 = now(), t1;
		do {
			tri();
			glFinish();
			n++;
			t1 = now();
		} while (t1 - t0 < min_s / 3 || n < 2);
		if ((t1 - t0) / n < best) best = (t1 - t0) / n;
	}
	return best * 1000;
}

static void music(void)
{
	U tex, fb = target(0x8814, 1024, ROWS, &tex);   // RGBA32F, as in the intro
	double t0 = now();
	U p = program(music_src);
	double t1 = now();
	if (!p) return;
	glViewport(0, 0, 1, 1);
	tri();
	glFinish();
	double t2 = now();
	glViewport(0, 0, 1024, ROWS);
	tri();
	glFinish();
	double t3 = now();
	glReadPixels(0, 0, 1024, ROWS, 0x1908, 0x1406, song);
	double t4 = now(), band = 0;
	printf_("music: compile+link %.0f ms, first tiny draw %.0f ms, render %.0f ms, readback %.0f ms\n",
		(t1 - t0) * 1e3, (t2 - t1) * 1e3, (t3 - t2) * 1e3, (t4 - t3) * 1e3);
	// the same in 8 horizontal bands (gl_FragCoord is window relative)
	int bh = (ROWS + 7) / 8;
	double tb = now();
	for (int b = 0; b < 8; b++) {
		double s = now();
		glViewport(0, b * bh, 1024, bh);
		tri();
		glFinish();
		double e = now() - s;
		if (e > band) band = e;
	}
	double total = now() - tb;
	glReadPixels(0, 0, 1024, ROWS, 0x1908, 0x1406, song2);
	long diff = 0;
	double rms = 0;
	for (long i = 0; i < (long)SONG_SAMPLES * 2; i++) {
		U a = ((U *)song)[i], b = ((U *)song2)[i];
		diff += a != b;
		rms += (double)song[i] * song[i];
	}
	printf_("music in 8 bands: slowest band %.0f ms, all %.0f ms, identical to one draw: %s\n",
		band * 1e3, total * 1e3, diff ? "NO" : "yes");
	// rms of the llvmpipe reference: 0.2130 (NVIDIA: 0.2130)
	printf_("music check: rms %.4f (reference 0.2130), samples %.5f %.5f %.5f %.5f\n",
		rms > 0 ? __builtin_sqrt(rms / ((double)SONG_SAMPLES * 2)) : 0., song[176400 * 2], song[176400 * 2 + 1],
		song[2646000 * 2], song[2646000 * 2 + 1]);
	glDeleteProgram(p);
	(void)fb;
}

// the intro's speed test (src/mac/main.asm with SCALE): 3 frames of 1:28 at
// half size, the fastest in whole ms from glutGet, k = the largest k (11..16)
// with k * k * ms <= 2304 (about 36 ms per frame at full size)
static void speedtest(U p, int loc, const char *when)
{
	int sw = W / 2, sh = H / 2, best = 1 << 30, last, k = 16;
	double bestp = 1e9, tl;
	glUseProgram(p);
	glViewport(0, 0, sw, sh);
	glUniform4f(loc, 88, sw, sh, 0);
	tri();
	glFinish();
	last = glutGet(700);
	tl = now();
	for (int i = 0; i < 3; i++) {
		tri();
		glFinish();
		int t = glutGet(700);
		double tp = now();
		if (t - last < best) best = t - last;
		if (tp - tl < bestp) bestp = tp - tl;
		last = t;
		tl = tp;
	}
	while (k > 11 && k * k * best > 2304) k--;
	printf_("the intro's speed test (%s): fastest half-size frame of 1:28 %d ms (exactly %.1f ms) -> render size %d/16\n",
		when, best, bestp * 1e3, k);
	out();
}

// renders 1:28 at full size without a break for secs seconds, printing the
// average ms per frame every 3 s (the GPU's clock drops as it heats up)
static void heat(U p, int loc, double secs)
{
	glUseProgram(p);
	glViewport(0, 0, W, H);
	glUniform4f(loc, 88, W, H, 0);
	printf_("heating the GPU up: 1:28 at full size for %.0f s, ms per frame every 3 s:\n ", secs);
	out();
	double t0 = now(), w0 = t0;
	int n = 0;
	while (now() - t0 < secs) {
		tri();
		glFinish();
		n++;
		double t = now();
		if (t - w0 >= 3) {
			printf_(" %.1f", (t - w0) / n * 1e3);
			out();
			w0 = t;
			n = 0;
		}
	}
	printf_("\n");
}

static void bench(void)
{
	U tex, fb = target(0x8058, W, H, &tex);   // RGBA8 at the screen size
	static U prog[NVAR];
	static int loc[NVAR];
	static double ms[NVAR][NM];
	for (int v = 0; v < NVAR; v++) {
		double t0 = now();
		prog[v] = program(visual_src[v]);
		double t1 = now();
		if (!prog[v]) { printf_("%s: FAILED\n", visual_name[v]); exit_(1); }
		loc[v] = glGetUniformLocation(prog[v], "u");
		glViewport(0, 0, 1, 1);
		glUniform4f(loc[v], 12, 1, 1, 0);
		tri();
		glFinish();
		double t2 = now();
		printf_("%-12s compile+link %4.0f ms, first draw %4.0f ms\n", visual_name[v], (t1 - t0) * 1e3, (t2 - t1) * 1e3);
		for (int m = 0; m < NM; m++) ms[v][m] = 1e9;
	}
	out();
	speedtest(prog[0], loc[0], "now");
	heat(prog[0], loc[0], 30);
	speedtest(prog[0], loc[0], "hot");
	// 3 rounds; in each, every moment is measured with all variants in turn,
	// a few seconds apart: the fastest round counts
	printf_("measuring %d variants at %d moments, 3 rounds ", NVAR, NM);
	out();
	for (int r = 0; r < 3; r++) {
		for (int m = 0; m < NM; m++)
			for (int v = 0; v < NVAR; v++) {
				glUseProgram(prog[v]);
				double x = timeit(loc[v], moments[m], W, H, .1);
				if (x < ms[v][m]) ms[v][m] = x;
			}
		printf_(".");
		out();
	}
	printf_("\n\nms per frame at %dx%d (hot):\nvariant     ", W, H);
	for (int m = 0; m < NM; m++) printf_(" %2d:%02d", (int)moments[m] / 60, (int)moments[m] % 60);
	printf_("  weighted  vs current\n");
	double base = 0;
	for (int v = 0; v < NVAR; v++) {
		double a = 0, wsum = 0;
		printf_("%-11s ", visual_name[v]);
		for (int m = 0; m < NM; m++) {
			printf_("%6.1f", ms[v][m]);
			a += ms[v][m] * weights[m];
			wsum += weights[m];
		}
		a /= wsum;
		if (!v) base = a;
		printf_("  %8.1f  %+5.1f %%\n", a, (a / base - 1) * 100);
	}
	speedtest(prog[0], loc[0], "at the end");
	(void)fb;
}

static void key(unsigned char k, int x, int y)
{
	(void)k, (void)x, (void)y;
	exit_(0);
}

// look mode: 3 moments x 5 internal resolutions, 3 s each after a 0.5 s gap
static const int look_k[5] = {16, 14, 12, 11, 10};
static const float look_t[3] = {26, 60, 88};
static U look_fb, look_loc;

// play mode: per scene frames, time, frames over 20 ms (missed a 60 Hz refresh), slowest
static const float scene_end[5] = {48, 80, 96, 128, 146};
static const char *scene_name[5] = {"horizon (0:00)", "tunnel 1 (0:48)", "atom (1:20)", "tunnel 2 (1:36)", "outro (2:08)"};
static int sc_frames[5], sc_slow[5], play_s;
static double sc_time[5], sc_worst[5], play_last;
static U play_fb, play_loc;
static int swaps;

static void play_frame(void)
{
	int ww = glutGet(102), wh = glutGet(103);
	if (!play_fb) {
		U tex;
		play_fb = target(0x8058, W, H, &tex);
		play_loc = glGetUniformLocation(program(visual_src[play_v]), "u");
		glViewport(0, 0, 1, 1);
		glUniform4f(play_loc, 12, 1, 1, 0);
		tri();
		glFinish();   // (compiles)
		start = play_last = now();
	}
	double t = now(), e = t - start, dt = t - play_last;
	play_last = t;
	if (e > .5) {   // the interval that just ended belongs to the previous frame's scene
		sc_frames[play_s]++;
		sc_time[play_s] += dt;
		sc_slow[play_s] += dt > .020;
		if (dt > sc_worst[play_s]) sc_worst[play_s] = dt;
	}
	if (e > 146) {
		printf_("\nplay: %s at %d/16 of %dx%d\nscene             fps  frames over 20 ms  slowest frame\n", visual_name[play_v], play_k, ww, wh);
		for (int s = 0; s < 5; s++)
			printf_("%-16s %5.1f  %10.0f %%  %10.0f ms\n", scene_name[s], sc_frames[s] / sc_time[s],
				100. * sc_slow[s] / sc_frames[s], sc_worst[s] * 1e3);
		out();
		exit_(0);
	}
	for (play_s = 0; play_s < 4 && e >= scene_end[play_s]; play_s++)
		;
	int sw = ww * play_k / 16, sh = wh * play_k / 16;
	glBindFramebuffer(0x8D40, play_k < 16 ? play_fb : 0);   // 16: straight into the window, as the intro
	glViewport(0, 0, sw, sh);
	glUniform4f(play_loc, e, sw, sh, 0);
	tri();
	if (play_k < 16) {
		glBindFramebuffer(0x8CA9, 0);
		glBlitFramebuffer(0, 0, sw, sh, 0, 0, ww, wh, 0x4000, 0x2601);
	}
	glutSwapBuffers();
}

static void frame(void)
{
	if (play) {
		play_frame();
		return;
	}
	if (!look && !swaps) start = now();
	if (!look && now() - start < 1.5) {   // first 1.5 s: does swapping wait for the display?
		glBindFramebuffer(0x8D40, 0);
		glClearColor(0, 0, 0, 1);
		glClear(0x4000);
		glutSwapBuffers();
		swaps++;
		return;
	}
	if (!look) {
		double t0 = now();
		printf_("GL: %s | %s | %s | GLSL %s\n", glGetString(0x1F00), glGetString(0x1F01), glGetString(0x1F02), glGetString(0x8B8C));
		printf_("screen %dx%d, window %dx%d\n", glutGet(200), glutGet(201), glutGet(102), glutGet(103));
#ifdef __APPLE__
		printf_("short framework paths: GLUT %s, OpenGL %s, AudioToolbox %s\n",
			dlopen(FWK "GLUT.framework/GLUT", 1) ? "ok" : "FAILED", dlopen(FWK "OpenGL.framework/OpenGL", 1) ? "ok" : "FAILED",
			dlopen(FWK "AudioToolbox.framework/AudioToolbox", 1) ? "ok" : "FAILED");
#endif
		printf_("window: %d buffer swaps in the first 1.5 s (%s)\n", swaps,
			swaps < 400 ? "synchronized with the display" : "not synchronized with the display");
		printf_("GL errors after start-up: 0x%x\n", err());
		out();
		music();
		printf_("GL errors after the music: 0x%x\n", err());
		out();
		bench();
		printf_("\ndone in %.0f s\n", now() - t0);
		out();
		exit_(0);
	}
	if (!look_fb) {
		U tex;
		look_fb = target(0x8058, W, H, &tex);
		look_loc = glGetUniformLocation(program(visual_src[0]), "u");
		start = now();
	}
	double e = now() - start;
	int seg = (int)(e / 3.5);
	if (seg >= 15) exit_(0);
	double into = e - seg * 3.5;
	int k = look_k[seg % 5], sw = W * k / 16, sh = H * k / 16;
	glBindFramebuffer(0x8D40, look_fb);
	if (into < .5) {
		glClearColor(0, 0, 0, 1);
		glClear(0x4000);
	} else {
		glViewport(0, 0, sw, sh);
		glUniform4f(look_loc, look_t[seg / 5] + (float)(into - .5), sw, sh, 0);
		tri();
	}
	glBindFramebuffer(0x8CA9, 0);
	glBlitFramebuffer(0, 0, sw, sh, 0, 0, glutGet(102), glutGet(103), 0x4000, 0x2601);
	glutSwapBuffers();
}

int main(int argc, char **argv)
{
	*(void **)&printf_ = dlsym(ANY, "printf");
	*(void **)&fflush_ = dlsym(ANY, "fflush");
	*(void **)&exit_ = dlsym(ANY, "exit");
#ifdef __APPLE__
	*(void **)&clock_ns = dlsym(ANY, "clock_gettime_nsec_np");
	void *gl = lib(FWK "OpenGL.framework/Versions/A/OpenGL"), *glut = lib(FWK "GLUT.framework/Versions/A/GLUT");
#else
	*(void **)&clock_gettime_ = dlsym(ANY, "clock_gettime");
	void *gl = lib("libGL.so.1"), *glut = lib("libglut.so.3");
	LOAD(glut, glutInitContextVersion);
	LOAD(glut, glutInitContextProfile);
	LOAD(glut, glutInitContextFlags);
#endif
	LOAD(glut, glutInit);
	LOAD(glut, glutInitDisplayMode);
	LOAD(glut, glutCreateWindow);
	LOAD(glut, glutFullScreen);
	LOAD(glut, glutSetCursor);
	LOAD(glut, glutDisplayFunc);
	LOAD(glut, glutIdleFunc);
	LOAD(glut, glutKeyboardFunc);
	LOAD(glut, glutMainLoop);
	LOAD(glut, glutSwapBuffers);
	LOAD(glut, glutGet);
	LOAD(gl, glGetString);
	LOAD(gl, glGetError);
	LOAD(gl, glCreateShader);
	LOAD(gl, glShaderSource);
	LOAD(gl, glCompileShader);
	LOAD(gl, glGetShaderiv);
	LOAD(gl, glGetShaderInfoLog);
	LOAD(gl, glCreateProgram);
	LOAD(gl, glAttachShader);
	LOAD(gl, glLinkProgram);
	LOAD(gl, glGetProgramiv);
	LOAD(gl, glGetProgramInfoLog);
	LOAD(gl, glUseProgram);
	LOAD(gl, glDeleteProgram);
	LOAD(gl, glGetUniformLocation);
	LOAD(gl, glUniform4f);
	LOAD(gl, glGenVertexArrays);
	LOAD(gl, glBindVertexArray);
	LOAD(gl, glDrawArrays);
	LOAD(gl, glViewport);
	LOAD(gl, glGenTextures);
	LOAD(gl, glBindTexture);
	LOAD(gl, glTexImage2D);
	LOAD(gl, glGenFramebuffers);
	LOAD(gl, glBindFramebuffer);
	LOAD(gl, glFramebufferTexture2D);
	LOAD(gl, glCheckFramebufferStatus);
	LOAD(gl, glReadPixels);
	LOAD(gl, glBlitFramebuffer);
	LOAD(gl, glClearColor);
	LOAD(gl, glClear);
	LOAD(gl, glFinish);

	look = argc > 1 && argv[1][0] == 'l';
	play = argc > 1 && argv[1][0] == 'p';
	if (play && argc > 2) {
		play_v = -1;
		for (int v = 0; v < NVAR; v++)
			if (same(argv[2], visual_name[v]) || (argv[2][0] >= '0' && argv[2][0] <= '9' && num(argv[2]) == v)) play_v = v;
		if (play_v < 0) {
			printf_("unknown variant %s; the variants are:", argv[2]);
			for (int v = 0; v < NVAR; v++) printf_(" %d %s,", v, visual_name[v]);
			printf_("\n");
			exit_(1);
		}
		if (argc > 3) play_k = num(argv[3]);
		if (play_k < 1 || play_k > 16) play_k = 16;
	}
	glutInit(&argc, argv);
#ifdef __APPLE__
	glutInitDisplayMode(0x802);   // GLUT_DOUBLE | GLUT_3_2_CORE_PROFILE, as the intro
#else
	glutInitContextVersion(3, 3);
	glutInitContextProfile(1);    // core
	glutInitContextFlags(2);      // forward compatible
	glutInitDisplayMode(2);       // GLUT_DOUBLE
#endif
	glutCreateWindow("macbench");
	glutFullScreen();
	glutSetCursor(101);           // GLUT_CURSOR_NONE
	glutKeyboardFunc(key);
	glutDisplayFunc(frame);
	glutIdleFunc(frame);
	U vao;
	glGenVertexArrays(1, &vao);
	glBindVertexArray(vao);
	W = glutGet(200);             // GLUT_SCREEN_WIDTH / HEIGHT: the intro renders at the screen size
	H = glutGet(201);
#ifndef __APPLE__
	if (argc > 3) {               // Linux twin: explicit render size
		W = H = 0;
		for (char *c = argv[2]; *c; c++) W = W * 10 + *c - '0';
		for (char *c = argv[3]; *c; c++) H = H * 10 + *c - '0';
	}
#endif
	if (play)
		printf_("macbench play: the intro's pictures without sound, 2:26; any key quits. Variant %s, %d/16 of the screen resolution.\n",
			visual_name[play_v], play_k);
	else
	printf_(look ? "macbench look: 3 scenes (0:26 horizon, 1:00 tunnel, 1:28 core), each at 100%%, 87.5%%, 75%%, 69%%, 62.5%% of the\n"
			"screen resolution, in this order, 3 s each after a short black gap. Note the first one that looks too soft.\n"
		: "macbench: about 2 minutes; keep this window in front. Any key aborts.\n");
	out();
	glutMainLoop();
	return 0;
}
