// Development tool (NOT part of the intro): measures BRANA's shaders on the
// GPU of a Mac. tools/mac/build.sh cross-compiles it on Linux without the
// Apple SDK (every function comes from dlopen/dlsym, like src/mac/main.asm)
// and also builds a Linux twin with freeglut, for testing it on a PC.
//
//   ./macbench          timings: takes a minute or two, prints a table
//   ./macbench look     the visuals at 5 internal resolutions (to choose the
//                       smallest acceptable one); any key quits
//   The Linux twin also takes a render size: "bench 640 360".
//
// Everything is rendered offscreen into a framebuffer object of the screen
// size and timed with glFinish, so the display's refresh rate does not matter.
#include "variants.h"   // generated by tools/mac/variants.py

typedef unsigned U;
typedef unsigned long long u64;
void *dlopen(const char *, int);
void *dlsym(void *, const char *);

#ifdef __APPLE__
#define ANY ((void *)-2)   // RTLD_DEFAULT
#define FWK "/System/Library/Frameworks/"
#else
#define ANY ((void *)0)
#endif

static int (*printf_)(const char *, ...);
static int (*fflush_)(void *);
static void (*exit_)(int);
#ifdef __APPLE__
static u64 (*clock_ns)(int);
#else
static int (*clock_gettime_)(int, long *);
static void (*glutInitContextVersion)(int, int);
static void (*glutInitContextProfile)(int);
static void (*glutInitContextFlags)(int);
#endif
static void (*glutInit)(int *, char **);
static void (*glutInitDisplayMode)(U);
static int (*glutCreateWindow)(const char *);
static void (*glutFullScreen)(void);
static void (*glutSetCursor)(int);
static void (*glutDisplayFunc)(void (*)(void));
static void (*glutIdleFunc)(void (*)(void));
static void (*glutKeyboardFunc)(void (*)(unsigned char, int, int));
static void (*glutMainLoop)(void);
static void (*glutSwapBuffers)(void);
static int (*glutGet)(U);
static const char *(*glGetString)(U);
static U (*glGetError)(void);
static U (*glCreateShader)(U);
static void (*glShaderSource)(U, int, const char *const *, const int *);
static void (*glCompileShader)(U);
static void (*glGetShaderiv)(U, U, int *);
static void (*glGetShaderInfoLog)(U, int, int *, char *);
static U (*glCreateProgram)(void);
static void (*glAttachShader)(U, U);
static void (*glLinkProgram)(U);
static void (*glGetProgramiv)(U, U, int *);
static void (*glGetProgramInfoLog)(U, int, int *, char *);
static void (*glUseProgram)(U);
static void (*glDeleteProgram)(U);
static int (*glGetUniformLocation)(U, const char *);
static void (*glUniform4f)(int, float, float, float, float);
static void (*glGenVertexArrays)(int, U *);
static void (*glBindVertexArray)(U);
static void (*glDrawArrays)(U, int, int);
static void (*glViewport)(int, int, int, int);
static void (*glGenTextures)(int, U *);
static void (*glBindTexture)(U, U);
static void (*glTexImage2D)(U, int, int, int, int, int, U, U, const void *);
static void (*glGenFramebuffers)(int, U *);
static void (*glBindFramebuffer)(U, U);
static void (*glFramebufferTexture2D)(U, U, U, U, int);
static U (*glCheckFramebufferStatus)(U);
static void (*glReadPixels)(int, int, int, int, U, U, void *);
static void (*glBlitFramebuffer)(int, int, int, int, int, int, int, int, U, U);
static void (*glClearColor)(float, float, float, float);
static void (*glClear)(U);
static void (*glFinish)(void);

#define ROWS (SONG_SAMPLES / 2048 + 1)
static float song[ROWS * 1024 * 4], song2[ROWS * 1024 * 4];
static char log_[4096];
static const char *vs_src = "#version 330\nvoid main(){gl_Position=vec4(gl_VertexID%2*4-1,gl_VertexID/2*4-1,0,1);}";
static const float moments[8] = {12, 26, 40, 60, 88, 100, 116, 132};
static const float weights[8] = {16, 16, 16, 32, 16, 16, 16, 18};   // seconds each moment stands for
static int W, H, look;
static double start;

static void *lib(const char *name)
{
	void *h = dlopen(name, 1);
	if (!h) { printf_("cannot load %s\n", name); exit_(1); }
	return h;
}

static void *sym(void *h, const char *name)
{
	void *p = dlsym(h, name);
	if (!p) { printf_("missing function %s\n", name); exit_(1); }
	return p;
}
#define LOAD(h, f) (*(void **)&f = sym(h, #f))

static double now(void)
{
#ifdef __APPLE__
	return clock_ns(8) * 1e-9;   // CLOCK_UPTIME_RAW
#else
	long ts[2];
	clock_gettime_(1, ts);       // CLOCK_MONOTONIC
	return ts[0] + ts[1] * 1e-9;
#endif
}

static void out(void) { fflush_(0); }

static U shader(U type, const char *src)
{
	U s = glCreateShader(type);
	int ok = 0;
	glShaderSource(s, 1, &src, 0);
	glCompileShader(s);
	glGetShaderiv(s, 0x8B81, &ok);   // GL_COMPILE_STATUS
	if (!ok) {
		glGetShaderInfoLog(s, sizeof log_, 0, log_);
		printf_("shader compile FAILED:\n%s\n", log_);
	}
	return s;
}

// program with the intro's vertex shader; returns 0 on failure
static U program(const char *fs)
{
	U p = glCreateProgram();
	int ok = 0;
	glAttachShader(p, shader(0x8B31, vs_src));
	glAttachShader(p, shader(0x8B30, fs));
	glLinkProgram(p);
	glGetProgramiv(p, 0x8B82, &ok);   // GL_LINK_STATUS
	if (!ok) {
		glGetProgramInfoLog(p, sizeof log_, 0, log_);
		printf_("program link FAILED:\n%s\n", log_);
		return 0;
	}
	glUseProgram(p);
	return p;
}

static void tri(void) { glDrawArrays(4, 0, 3); }   // GL_TRIANGLES

// clears pending GL errors, returns the first one
static U err(void)
{
	U e = glGetError(), f = e;
	while (f) f = glGetError();
	return e;
}

// offscreen render target: texture + framebuffer object
static U target(U ifmt, int w, int h, U *tex)
{
	U fb;
	glGenTextures(1, tex);
	glBindTexture(0x0DE1, *tex);
	glTexImage2D(0x0DE1, 0, ifmt, w, h, 0, 0x1908, ifmt == 0x8058 ? 0x1401 : 0x1406, 0);
	glGenFramebuffers(1, &fb);
	glBindFramebuffer(0x8D40, fb);
	glFramebufferTexture2D(0x8D40, 0x8CE0, 0x0DE1, *tex, 0);
	U st = glCheckFramebufferStatus(0x8D40);
	if (st != 0x8CD5) printf_("framebuffer %dx%d format 0x%x NOT complete: 0x%x\n", w, h, ifmt, st);
	return fb;
}

// ms per frame of the current program at time t, rendered at w x h: the
// fastest of 3 batches (each at least min_s / 3 and 2 frames), so that
// other programs running meanwhile distort it less
static double timeit(int loc, float t, int w, int h, double min_s)
{
	glViewport(0, 0, w, h);
	glUniform4f(loc, t, w, h, 0);
	tri();
	glFinish();   // warm-up at this size
	double best = 1e9;
	for (int b = 0; b < 3; b++) {
		int n = 0;
		double t0 = now(), t1;
		do {
			tri();
			glFinish();
			n++;
			t1 = now();
		} while (t1 - t0 < min_s / 3 || n < 2);
		if ((t1 - t0) / n < best) best = (t1 - t0) / n;
	}
	return best * 1000;
}

static void music(void)
{
	U tex, fb = target(0x8814, 1024, ROWS, &tex);   // RGBA32F, as in the intro
	double t0 = now();
	U p = program(music_src);
	double t1 = now();
	if (!p) return;
	glViewport(0, 0, 1, 1);
	tri();
	glFinish();
	double t2 = now();
	glViewport(0, 0, 1024, ROWS);
	tri();
	glFinish();
	double t3 = now();
	glReadPixels(0, 0, 1024, ROWS, 0x1908, 0x1406, song);
	double t4 = now(), band = 0;
	printf_("music: compile+link %.0f ms, first tiny draw %.0f ms, render %.0f ms, readback %.0f ms\n",
		(t1 - t0) * 1e3, (t2 - t1) * 1e3, (t3 - t2) * 1e3, (t4 - t3) * 1e3);
	// the same in 8 horizontal bands (gl_FragCoord is window relative)
	int bh = (ROWS + 7) / 8;
	double tb = now();
	for (int b = 0; b < 8; b++) {
		double s = now();
		glViewport(0, b * bh, 1024, bh);
		tri();
		glFinish();
		double e = now() - s;
		if (e > band) band = e;
	}
	double total = now() - tb;
	glReadPixels(0, 0, 1024, ROWS, 0x1908, 0x1406, song2);
	long diff = 0;
	double rms = 0;
	for (long i = 0; i < (long)SONG_SAMPLES * 2; i++) {
		U a = ((U *)song)[i], b = ((U *)song2)[i];
		diff += a != b;
		rms += (double)song[i] * song[i];
	}
	printf_("music in 8 bands: slowest band %.0f ms, all %.0f ms, identical to one draw: %s\n",
		band * 1e3, total * 1e3, diff ? "NO" : "yes");
	// rms of the llvmpipe reference: 0.2130 (NVIDIA: 0.2130)
	printf_("music check: rms %.4f (reference 0.2130), samples %.5f %.5f %.5f %.5f\n",
		rms > 0 ? __builtin_sqrt(rms / ((double)SONG_SAMPLES * 2)) : 0., song[176400 * 2], song[176400 * 2 + 1],
		song[2646000 * 2], song[2646000 * 2 + 1]);
	glDeleteProgram(p);
	(void)fb;
}

static void bench(void)
{
	U tex, fb = target(0x8058, W, H, &tex);   // RGBA8 at the screen size
	static double ms[NVAR][2][8];
	for (int v = 0; v < NVAR; v++) {
		double t0 = now();
		U p = program(visual_src[v]);
		double t1 = now();
		if (!p) { printf_("%s: FAILED\n", visual_name[v]); continue; }
		int loc = glGetUniformLocation(p, "u");
		glViewport(0, 0, 1, 1);
		glUniform4f(loc, 12, 1, 1, 0);
		tri();
		glFinish();
		double t2 = now();
		if (!v) printf_("uniform location of u: %d\n", loc);
		printf_("%-12s compile+link %5.0f ms, first draw %5.0f ms ...", visual_name[v], (t1 - t0) * 1e3, (t2 - t1) * 1e3);
		out();
		for (int s = 0; s < 2; s++)
			for (int m = 0; m < 8; m++)
				ms[v][s][m] = timeit(loc, moments[m], s ? W / 2 : W, s ? H / 2 : H, .3);
		printf_(" done\n");
		out();
		glDeleteProgram(p);
	}
	for (int s = 0; s < 2; s++) {
		printf_("\nms per frame at %dx%d%s:\nvariant      ", s ? W / 2 : W, s ? H / 2 : H, s ? " (half size)" : "");
		for (int m = 0; m < 8; m++) printf_("%5.0fs", moments[m]);
		printf_("  weighted\n");
		for (int v = 0; v < NVAR; v++) {
			double a = 0, wsum = 0;
			printf_("%-12s ", visual_name[v]);
			for (int m = 0; m < 8; m++) {
				printf_("%6.1f", ms[v][s][m]);
				a += ms[v][s][m] * weights[m];
				wsum += weights[m];
			}
			printf_("  %6.1f\n", a / wsum);
		}
	}
	// the render target and the upscale that the resolution scaling would use
	U p = program(visual_src[0]);
	int loc = glGetUniformLocation(p, "u"), sw = W * 11 / 16, sh = H * 11 / 16;
	printf_("\nrender at 11/16 size (%dx%d) + upscale to the window, current shader, t=26:\n", sw, sh);
	printf_("  GL errors before this test: 0x%x\n", err());
	for (int k = 0; k < 4; k++) {   // both formats twice, only the second round is printed (warm-up)
		U ifmt = k & 1 ? 0x8814 : 0x8058, t2, fb2 = target(ifmt, W, H, &t2);
		double d = timeit(loc, 26, sw, sh, .3), b = 0;
		int n = 0;
		double t0 = now();
		do {
			glBindFramebuffer(0x8CA9, 0);   // draw: window, read: fb2
			glBlitFramebuffer(0, 0, sw, sh, 0, 0, W, H, 0x4000, 0x2601);
			glFinish();
			n++;
			b = now() - t0;
		} while (b < .2 || n < 2);
		if (k > 1) printf_("  %-7s render %.1f ms, blit %.2f ms, GL error 0x%x\n", k & 1 ? "RGBA32F" : "RGBA8", d, b / n * 1e3, err());
		glBindFramebuffer(0x8D40, fb2);
	}
	// the intro's plan: re-specify the (attached) music texture at the screen size
	U mt, mf = target(0x8814, 1024, ROWS, &mt);
	glTexImage2D(0x0DE1, 0, 0x8058, W, H, 0, 0x1908, 0x1401, 0);
	U st = glCheckFramebufferStatus(0x8D40);
	timeit(loc, 26, sw, sh, .05);
	glBindFramebuffer(0x8CA9, 0);
	glBlitFramebuffer(0, 0, sw, sh, 0, 0, W, H, 0x4000, 0x2601);
	glFinish();
	printf_("  attached texture re-specified at screen size: framebuffer 0x%x%s, draw+blit GL error 0x%x\n", st,
		st == 0x8CD5 ? " (complete)" : " (NOT complete)", err());
	(void)fb;
	(void)mf;
}

static void key(unsigned char k, int x, int y)
{
	(void)k, (void)x, (void)y;
	exit_(0);
}

// look mode: 3 moments x 5 internal resolutions, 3 s each after a 0.5 s gap
static const int look_k[5] = {16, 14, 12, 11, 10};
static const float look_t[3] = {26, 60, 88};
static U look_fb, look_loc;

static void frame(void)
{
	if (!look) {
		double t0 = now();
		printf_("GL: %s | %s | %s | GLSL %s\n", glGetString(0x1F00), glGetString(0x1F01), glGetString(0x1F02), glGetString(0x8B8C));
		printf_("screen %dx%d, window %dx%d\n", glutGet(200), glutGet(201), glutGet(102), glutGet(103));
#ifdef __APPLE__
		printf_("short framework paths: GLUT %s, OpenGL %s, AudioToolbox %s\n",
			dlopen(FWK "GLUT.framework/GLUT", 1) ? "ok" : "FAILED", dlopen(FWK "OpenGL.framework/OpenGL", 1) ? "ok" : "FAILED",
			dlopen(FWK "AudioToolbox.framework/AudioToolbox", 1) ? "ok" : "FAILED");
#endif
		printf_("GL errors after start-up: 0x%x\n", err());
		out();
		music();
		printf_("GL errors after the music: 0x%x\n", err());
		out();
		bench();
		printf_("\ndone in %.0f s\n", now() - t0);
		out();
		exit_(0);
	}
	if (!look_fb) {
		U tex;
		look_fb = target(0x8058, W, H, &tex);
		look_loc = glGetUniformLocation(program(visual_src[0]), "u");
		start = now();
	}
	double e = now() - start;
	int seg = (int)(e / 3.5);
	if (seg >= 15) exit_(0);
	double into = e - seg * 3.5;
	int k = look_k[seg % 5], sw = W * k / 16, sh = H * k / 16;
	glBindFramebuffer(0x8D40, look_fb);
	if (into < .5) {
		glClearColor(0, 0, 0, 1);
		glClear(0x4000);
	} else {
		glViewport(0, 0, sw, sh);
		glUniform4f(look_loc, look_t[seg / 5] + (float)(into - .5), sw, sh, 0);
		tri();
	}
	glBindFramebuffer(0x8CA9, 0);
	glBlitFramebuffer(0, 0, sw, sh, 0, 0, glutGet(102), glutGet(103), 0x4000, 0x2601);
	glutSwapBuffers();
}

int main(int argc, char **argv)
{
	*(void **)&printf_ = dlsym(ANY, "printf");
	*(void **)&fflush_ = dlsym(ANY, "fflush");
	*(void **)&exit_ = dlsym(ANY, "exit");
#ifdef __APPLE__
	*(void **)&clock_ns = dlsym(ANY, "clock_gettime_nsec_np");
	void *gl = lib(FWK "OpenGL.framework/Versions/A/OpenGL"), *glut = lib(FWK "GLUT.framework/Versions/A/GLUT");
#else
	*(void **)&clock_gettime_ = dlsym(ANY, "clock_gettime");
	void *gl = lib("libGL.so.1"), *glut = lib("libglut.so.3");
	LOAD(glut, glutInitContextVersion);
	LOAD(glut, glutInitContextProfile);
	LOAD(glut, glutInitContextFlags);
#endif
	LOAD(glut, glutInit);
	LOAD(glut, glutInitDisplayMode);
	LOAD(glut, glutCreateWindow);
	LOAD(glut, glutFullScreen);
	LOAD(glut, glutSetCursor);
	LOAD(glut, glutDisplayFunc);
	LOAD(glut, glutIdleFunc);
	LOAD(glut, glutKeyboardFunc);
	LOAD(glut, glutMainLoop);
	LOAD(glut, glutSwapBuffers);
	LOAD(glut, glutGet);
	LOAD(gl, glGetString);
	LOAD(gl, glGetError);
	LOAD(gl, glCreateShader);
	LOAD(gl, glShaderSource);
	LOAD(gl, glCompileShader);
	LOAD(gl, glGetShaderiv);
	LOAD(gl, glGetShaderInfoLog);
	LOAD(gl, glCreateProgram);
	LOAD(gl, glAttachShader);
	LOAD(gl, glLinkProgram);
	LOAD(gl, glGetProgramiv);
	LOAD(gl, glGetProgramInfoLog);
	LOAD(gl, glUseProgram);
	LOAD(gl, glDeleteProgram);
	LOAD(gl, glGetUniformLocation);
	LOAD(gl, glUniform4f);
	LOAD(gl, glGenVertexArrays);
	LOAD(gl, glBindVertexArray);
	LOAD(gl, glDrawArrays);
	LOAD(gl, glViewport);
	LOAD(gl, glGenTextures);
	LOAD(gl, glBindTexture);
	LOAD(gl, glTexImage2D);
	LOAD(gl, glGenFramebuffers);
	LOAD(gl, glBindFramebuffer);
	LOAD(gl, glFramebufferTexture2D);
	LOAD(gl, glCheckFramebufferStatus);
	LOAD(gl, glReadPixels);
	LOAD(gl, glBlitFramebuffer);
	LOAD(gl, glClearColor);
	LOAD(gl, glClear);
	LOAD(gl, glFinish);

	look = argc > 1 && argv[1][0] == 'l';
	glutInit(&argc, argv);
#ifdef __APPLE__
	glutInitDisplayMode(0x802);   // GLUT_DOUBLE | GLUT_3_2_CORE_PROFILE, as the intro
#else
	glutInitContextVersion(3, 3);
	glutInitContextProfile(1);    // core
	glutInitContextFlags(2);      // forward compatible
	glutInitDisplayMode(2);       // GLUT_DOUBLE
#endif
	glutCreateWindow("macbench");
	glutFullScreen();
	glutSetCursor(101);           // GLUT_CURSOR_NONE
	glutKeyboardFunc(key);
	glutDisplayFunc(frame);
	glutIdleFunc(frame);
	U vao;
	glGenVertexArrays(1, &vao);
	glBindVertexArray(vao);
	W = glutGet(200);             // GLUT_SCREEN_WIDTH / HEIGHT: the intro renders at the screen size
	H = glutGet(201);
#ifndef __APPLE__
	if (argc > 3) {               // Linux twin: explicit render size
		W = H = 0;
		for (char *c = argv[2]; *c; c++) W = W * 10 + *c - '0';
		for (char *c = argv[3]; *c; c++) H = H * 10 + *c - '0';
	}
#endif
	printf_(look ? "macbench look: 3 scenes (0:26 horizon, 1:00 tunnel, 1:28 core), each at 100%%, 87.5%%, 75%%, 69%%, 62.5%% of the\n"
			"screen resolution, in this order, 3 s each after a short black gap. Note the first one that looks too soft.\n"
		: "macbench: about a minute or two; keep this window in front. Any key aborts.\n");
	out();
	glutMainLoop();
	return 0;
}
