#!/usr/bin/env python3
# Development helper (NOT part of the intro): builds the shader variants that
# tools/mac/macbench measures, from the current src/visual.frag by exact text
# substitutions, and writes
#   <out>/variants.h        minified sources for macbench.c (C strings)
#   <out>/v<k>_<name>.frag  the variant sources, for tools/bench.py etc.
#
#   variants.py <out dir>
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
sys.path.insert(0, os.path.join(ROOT, 'tools'))
from minify import minify_one, c_string   # noqa: E402

out = sys.argv[1]
os.makedirs(out, exist_ok=True)
visual = open(os.path.join(ROOT, 'src', 'visual.frag')).read()
music = open(os.path.join(ROOT, 'src', 'music.frag')).read()


def sub(src, old, new):
	if src.count(old) != 1:
		sys.exit('variants.py: pattern not found once in visual.frag: %r' % old[:60])
	return src.replace(old, new)


NORMAL = ('\t\t\t\tvec2 e = vec2(.001, -.001);\n'
	'\t\t\t\tn = vec3(0, 1, 0);\n'
	'\t\t\t\tif (m > 0.) n = normalize(e.xyy * map(p + e.xyy) + e.yyx * map(p + e.yyx) + e.yxy * map(p + e.yxy) + e.xxx * map(p + e.xxx));\n')
# the same 4 taps and weights in the same order, as a loop
NORMAL_LOOP = ('\t\t\t\tn = vec3(0, 1, 0);\n'
	'\t\t\t\tif (m > 0.) {\n'
	'\t\t\t\t\tn = vec3(0);\n'
	'\t\t\t\t\tfor (int i = 0; i < 4; i++) {\n'
	'\t\t\t\t\t\tvec3 e = (vec3(i + 3 >> 1 & 1, i >> 1 & 1, i & 1) * 2. - 1.) * .001;\n'
	'\t\t\t\t\t\tn += e * map(p + e);\n'
	'\t\t\t\t\t}\n'
	'\t\t\t\t\tn = normalize(n);\n'
	'\t\t\t\t}\n')
BOUNCE = 'for (int b = 0; b < 2; b++)'
MARCH = 'for (int i = 0; i < 120; i++)'
AO = 'for (int j = 1; j < 5; j++)'
CORE = '\t\td = f;\n\t\tg = length(p) - .5;\n\t\tfor (int i = 0; i < 6; i++) {'
CORE_BOUND = ('\t\td = f;\n\t\tg = length(p) - .5;\n'
	'\t\tif (g > 4.) {   // far outside all rings (they end at radius 4.115)\n'
	'\t\t\td = g - 3.6;\n\t\t\tg -= 3.615;\n'
	'\t\t} else\n'
	'\t\tfor (int i = 0; i < 6; i++) {')


def normal_loop(s):
	return sub(s, NORMAL, NORMAL_LOOP)


def no_unroll(s):   # runtime trip counts (u.w is 0): the compiler cannot unroll
	s = sub(normal_loop(s), 'for (int i = 0; i < 4; i++)', 'for (int i = int(u.w); i < 4; i++)')
	s = sub(s, BOUNCE, 'for (int b = int(u.w); b < 2; b++)')
	return sub(s, AO, 'for (int j = 1 + int(u.w); j < 5; j++)')


def ao3(s):   # 3 AO taps instead of 4
	if AO in s:
		return sub(s, AO, 'for (int j = 1; j < 4; j++)')
	return sub(s, 'for (int j = 1 + int(u.w); j < 5; j++)', 'for (int j = 1 + int(u.w); j < 4; j++)')


def core_bound(s):
	return sub(s, CORE, CORE_BOUND)


def refl60(s):   # 60 steps for the floor reflection instead of 120
	return sub(s, MARCH, 'for (int i = 0; i < 120 - b * 60; i++)')


VARIANTS = [
	('current', lambda s: s),
	('normal_loop', normal_loop),
	('no_unroll', no_unroll),
	('ao3', ao3),
	('core_bound', core_bound),
	('refl60', refl60),
	('all', lambda s: refl60(core_bound(ao3(no_unroll(s))))),
]

srcs = []
for k, (name, f) in enumerate(VARIANTS):
	s = f(visual)
	if k and s == visual:
		sys.exit('variants.py: variant %s changed nothing' % name)
	open(os.path.join(out, 'v%d_%s.frag' % (k, name)), 'w').write(s)
	srcs.append(minify_one(s))
with open(os.path.join(out, 'variants.h'), 'w') as f:
	f.write('// generated by tools/mac/variants.py - do not edit\n')
	f.write('#define SONG_SAMPLES %d\n' % (73 * 88200))
	f.write('#define NVAR %d\n' % len(VARIANTS))
	f.write('static const char *music_src = %s;\n' % c_string(minify_one(music)))
	f.write('static const char *visual_name[NVAR] = {%s};\n' % ', '.join('"%s"' % n for n, _ in VARIANTS))
	f.write('static const char *visual_src[NVAR] = {\n%s};\n' % ''.join('\t%s,\n' % c_string(s) for s in srcs))
print('%d variants in %s' % (len(VARIANTS), out), file=sys.stderr)
