#!/usr/bin/env python3
# Development helper (NOT part of the intro): builds the shader variants that
# tools/mac/macbench measures, from the current src/visual.frag by exact text
# substitutions, and writes
#   <out>/variants.h        minified sources for macbench.c (C strings)
#   <out>/v<k>_<name>.frag  the variant sources, for tools/bench.py etc.
#
#   variants.py <out dir>
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
sys.path.insert(0, os.path.join(ROOT, 'tools'))
from minify import minify_one, c_string   # noqa: E402

out = sys.argv[1]
os.makedirs(out, exist_ok=True)
visual = open(os.path.join(ROOT, 'src', 'visual.frag')).read()
music = open(os.path.join(ROOT, 'src', 'music.frag')).read()


def sub(src, old, new):
	if src.count(old) != 1:
		sys.exit('variants.py: pattern not found once in visual.frag: %r' % old[:60])
	return src.replace(old, new)


NORMAL = ('\t\t\t\tvec2 e = vec2(.001, -.001);\n'
	'\t\t\t\tn = vec3(0, 1, 0);\n'
	'\t\t\t\tif (m > 0.) n = normalize(e.xyy * map(p + e.xyy) + e.yyx * map(p + e.yyx) + e.yxy * map(p + e.yxy) + e.xxx * map(p + e.xxx));\n')
# the same 4 taps and weights in the same order, as a loop
NORMAL_LOOP = ('\t\t\t\tn = vec3(0, 1, 0);\n'
	'\t\t\t\tif (m > 0.) {\n'
	'\t\t\t\t\tn = vec3(0);\n'
	'\t\t\t\t\tfor (int i = 0; i < 4; i++) {\n'
	'\t\t\t\t\t\tvec3 e = (vec3(i + 3 >> 1 & 1, i >> 1 & 1, i & 1) * 2. - 1.) * .001;\n'
	'\t\t\t\t\t\tn += e * map(p + e);\n'
	'\t\t\t\t\t}\n'
	'\t\t\t\t\tn = normalize(n);\n'
	'\t\t\t\t}\n')
BOUNCE = 'for (int b = 0; b < 2; b++)'
MARCH = 'for (int i = 0; i < 120; i++)'
AO = 'for (int j = 1; j < 5; j++)'
CORE = '\t\td = f;\n\t\tg = length(p) - .5;\n\t\tfor (int i = 0; i < 6; i++) {'
CORE_BOUND = ('\t\td = f;\n\t\tg = length(p) - .5;\n'
	'\t\tif (g > 4.) {   // far outside all rings (they end at radius 4.115)\n'
	'\t\t\td = g - 3.6;\n\t\t\tg -= 3.615;\n'
	'\t\t} else\n'
	'\t\tfor (int i = 0; i < 6; i++) {')


GLOBALS = 'float B, S, V, G, M, Q;'
CORE_ROT = '\t\t\tp.xy *= rot(B * .6 + i);\n\t\t\tp.yz *= rot(B * .4);\n'
CORE_START = '\t\td = f;\n\t\tg = length(p) - .5;\n'
TUN_NL = '\t\tfloat n = S * 2. + 2. + V, l = 4.3 * tan(3.1416 / n) - (S - 1.) * .2;\n'


def normal_loop(s):
	return sub(s, NORMAL, NORMAL_LOOP)


def no_unroll(s):   # runtime trip counts (u.w is 0): the compiler cannot unroll
	s = sub(normal_loop(s), 'for (int i = 0; i < 4; i++)', 'for (int i = int(u.w); i < 4; i++)')
	s = sub(s, BOUNCE, 'for (int b = int(u.w); b < 2; b++)')
	return sub(s, AO, 'for (int j = 1 + int(u.w); j < 5; j++)')


def ao3(s):   # 3 AO taps instead of 4
	if AO in s:
		return sub(s, AO, 'for (int j = 1; j < 4; j++)')
	return sub(s, 'for (int j = 1 + int(u.w); j < 5; j++)', 'for (int j = 1 + int(u.w); j < 4; j++)')


def core_bound(s):
	return sub(s, CORE, CORE_BOUND)


def core_hoist(s):   # the core's 7 ring rotations once per pixel (in main), not in every map()
	s = sub(s, GLOBALS, 'mat2 R[6], Y;\n' + GLOBALS)
	s = sub(s, CORE_ROT, '\t\t\tp.xy *= R[i];\n\t\t\tp.yz *= Y;\n')
	return sub(s, '\t\tS = 2.;\n', '\t\tS = 2.;\n\t\tfor (int i = 0; i < 6; i++) R[i] = rot(B * .6 + i);\n\t\tY = rot(B * .4);\n')


def core_inc(s):   # the same rotations by angle addition: 2 sin/cos pairs per map() instead of 7
	s = sub(s, CORE_START, '\t\tmat2 rr = rot(B * .6), ry = rot(B * .4);\n' + CORE_START)
	return sub(s, CORE_ROT, '\t\t\tp.xy *= rr;\n\t\t\tp.yz *= ry;\n\t\t\trr *= rot(1.);\n')


def tun_hoist(s):   # the tunnels' sides and length (tan) once per pixel, not in every map()
	s = sub(s, GLOBALS, GLOBALS[:-1] + ', N, L;')
	s = sub(s, TUN_NL, '')
	s = sub(s, '* n + .5) / n * 6.283', '* N + .5) / N * 6.283')
	s = sub(s, 'vec3(.4, l + .4, .3)', 'vec3(.4, L + .4, .3)')
	s = sub(s, 'vec3(.02, l, .2)', 'vec3(.02, L, .2)')
	return sub(s, '\t\tV = mod(floor(B / 4.), 3.);\n', '\t\tV = mod(floor(B / 4.), 3.);\n'
		'\t\tN = S * 2. + 2. + V;\n\t\tL = 4.3 * tan(3.1416 / N) - (S - 1.) * .2;\n')


def refl60(s):   # 60 steps for the floor reflection instead of 120
	return sub(s, MARCH, 'for (int i = 0; i < 120 - b * 60; i++)')


# round 2: the atom (core) and the tunnels; ao3 checks the measurement (it does
# strictly less work than current, but measured slower in round 1)
VARIANTS = [
	('current', lambda s: s),
	('ao3', ao3),
	('core_bound', core_bound),
	('core_hoist', core_hoist),
	('core_inc', core_inc),
	('tun_hoist', tun_hoist),
	('opt', lambda s: tun_hoist(core_hoist(core_bound(s)))),
	('opt_inc', lambda s: tun_hoist(core_inc(core_bound(s)))),
]

srcs = []
for k, (name, f) in enumerate(VARIANTS):
	s = f(visual)
	if k and s == visual:
		sys.exit('variants.py: variant %s changed nothing' % name)
	open(os.path.join(out, 'v%d_%s.frag' % (k, name)), 'w').write(s)
	srcs.append(minify_one(s))
with open(os.path.join(out, 'variants.h'), 'w') as f:
	f.write('// generated by tools/mac/variants.py - do not edit\n')
	f.write('#define SONG_SAMPLES %d\n' % (73 * 88200))
	f.write('#define NVAR %d\n' % len(VARIANTS))
	f.write('static const char *music_src = %s;\n' % c_string(minify_one(music)))
	f.write('static const char *visual_name[NVAR] = {%s};\n' % ', '.join('"%s"' % n for n, _ in VARIANTS))
	f.write('static const char *visual_src[NVAR] = {\n%s};\n' % ''.join('\t%s,\n' % c_string(s) for s in srcs))
print('%d variants in %s' % (len(VARIANTS), out), file=sys.stderr)
